environment: production
chdir: /home/ubuntu/testsin/current/
address: 0.0.0.0
user: ubuntu
# group: admin
port: 3000
pid: /home/ubuntu/testsin/shared/pids/thin.pid
rackup: /home/ubuntu/testsin/current/config.ru
log: /home/ubuntu/testsin/shared/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true